# Generated by Django 2.1.5 on 2020-07-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200615_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('BIILING', 'billing'), ('SHIPPING', 'shipping')], max_length=120),
        ),
    ]
