# Generated by Django 2.1.5 on 2020-07-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonprofile',
            name='city',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypersonprofile',
            name='contact_number',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverypersonprofile',
            name='state',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
