# Generated by Django 2.1.5 on 2020-07-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliverypersonprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypersonprofile',
            name='postal_code',
            field=models.CharField(default=12121212, max_length=120),
            preserve_default=False,
        ),
    ]
