# Generated by Django 2.1.5 on 2020-06-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='phone_Number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
