# Generated by Django 2.1.5 on 2020-05-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
