# Generated by Django 2.1.5 on 2020-06-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customerprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
