# Generated by Django 2.1.5 on 2020-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200520_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='address_line_3',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile_pic/'),
        ),
    ]
