# Generated by Django 2.1.5 on 2020-06-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200616_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.FileField(null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
