# Generated by Django 2.1.5 on 2020-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200616_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='town_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
