# Generated by Django 2.1.5 on 2020-07-05 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200705_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='state',
        ),
    ]
