# Generated by Django 2.1.5 on 2020-05-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='product_images/', verbose_name=''),
        ),
    ]
