# Generated by Django 2.1.5 on 2020-04-23 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120)),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(max_length=120)),
                ('address_line_3', models.CharField(blank=True, max_length=120, null=True)),
                ('town_city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('contact', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('timming', models.IntegerField()),
                ('shop_details', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
