# Generated by Django 2.1.5 on 2020-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0002_shopprofile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='shop_image',
            field=models.FileField(null=True, upload_to='shops/', verbose_name=''),
        ),
    ]
