# Generated by Django 2.1.5 on 2020-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0004_auto_20200609_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='address_line_3',
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='contact',
            field=models.CharField(max_length=120),
        ),
    ]
