# Generated by Django 2.1.5 on 2020-07-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0005_auto_20200615_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_image', models.FileField(null=True, upload_to='shops/', verbose_name='')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopkeeper.ShopProfile')),
            ],
        ),
    ]
