# Generated by Django 2.1.5 on 2020-07-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0006_shopimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='shop_image',
        ),
        migrations.AddField(
            model_name='shopimage',
            name='shopimage',
            field=models.FileField(null=True, upload_to='shopimage/', verbose_name=''),
        ),
    ]
