# Generated by Django 2.1.5 on 2020-07-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0007_auto_20200701_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopimage',
            old_name='shopimage',
            new_name='shop_image',
        ),
        migrations.RemoveField(
            model_name='shopprofile',
            name='shop_image',
        ),
    ]
