# Generated by Django 2.1.5 on 2020-07-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopkeeper', '0009_auto_20200701_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='shop',
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
    ]
