# Generated by Django 2.1.5 on 2020-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
