# Generated by Django 2.1.5 on 2020-06-15 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
