# Generated by Django 2.1.5 on 2020-06-13 19:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0003_auto_20200613_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='User',
        ),
        migrations.AddField(
            model_name='cart',
            name='User',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
