# Generated by Django 2.1.5 on 2020-06-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200613_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='active',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='online',
        ),
    ]
