# Generated by Django 2.1.5 on 2020-06-15 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='User',
        ),
    ]
